apiVersion: k8s.nginx.org/v1alpha1
kind: VirtualServer
metadata:
  name: cafe
spec:
  host: cafe.example.com
  tls:
    secret: cafe-secret
  upstreams:
  - name: tea
    service: tea-svc
    port: 80
    next-upstream: "error timeout HTTP_404 non_idempotent"
    next-upstream-timeout: 5s
    next-upstream-tries: 10
  - name: coffee
    service: coffee-svc
    port: 80
    next-upstream: "error timeout HTTP_404 non_idempotent"
    next-upstream-timeout: 5s
    next-upstream-tries: 10
  routes:
  - path: /tea
    upstream: tea
  - path: /coffee
    upstream: coffee
